### ISSUE TITLE
IndiexError : list index out of range

### ISSUE THREAD

**Issue by yasir2afaq** [dairejpwalsh/Sentinel-Scripts#3]
I tried the script with my data set and the error says "List index out of range". Does it implies less number of bands???

Can you please shed some light on this issue???

`n [1]: runfile('C:/Users/ASUS/Desktop/Sentinel-Scripts-master/Sentinel 2/tiff-generator.py', wdir='C:/Users/ASUS/Desktop/Sentinel-Scripts-master/Sentinel 2')

Input Path? Inputs/S2A_MSIL1C_20180531T054641_N0206_R048_T43SDT_20180531T082555.zip
Extracting Done
Arg ../Output/S2A_MSIL1C_20180531T054641_N0206_R048_T43SDT_20180531T082555_PROCESSED/IMAGE_DATA//L1C_T43SDT_A015346_20180531T16Bit-AllBands.tifAdded
Traceback (most recent call last):

  File "<ipython-input-1-08bb859522f3>", line 1, in <module>
    runfile('C:/Users/ASUS/Desktop/Sentinel-Scripts-master/Sentinel 2/tiff-generator.py', wdir='C:/Users/ASUS/Desktop/Sentinel-Scripts-master/Sentinel 2')

  File "C:\Users\ASUS\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\ASUS\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/ASUS/Desktop/Sentinel-Scripts-master/Sentinel 2/tiff-generator.py", line 125, in <module>
    generate_geotiffs(inputPath, outputPath)

  File "C:/Users/ASUS/Desktop/Sentinel-Scripts-master/Sentinel 2/tiff-generator.py", line 54, in generate_geotiffs
    gdal_merge.main(params)

  File "Scripts\gdal_merge.py", line 423, in main
    ulx = file_infos[0].ulx

IndexError: list index out of range`

**Comment by dairejpwalsh** [comment]
Try the code now on a level 2A product

**Comment by yasir2afaq** [comment]
Working thank you
---
Regards

Yasir Khawaja
+919622949937
